let repoData = [
  {
    "id": 1296269,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
    "name": "git-viz-dashboard",
    "full_name": "octocat/git-viz-dashboard",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/git-viz-dashboard",
    "description": "An interactive GitHub analytics, profile visualizer, and repository metrics engine.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/git-viz-dashboard",
    "created_at": "2026-01-10T14:20:00Z",
    "updated_at": "2026-07-20T18:30:00Z",
    "pushed_at": "2026-07-25T09:15:00Z",
    "git_url": "git://github.com/octocat/git-viz-dashboard.git",
    "ssh_url": "git@github.com:octocat/git-viz-dashboard.git",
    "clone_url": "https://github.com/octocat/git-viz-dashboard.git",
    "homepage": "https://gitviz.dev",
    "size": 1420,
    "stargazers_count": 1280,
    "watchers_count": 1280,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": true,
    "forks_count": 142,
    "archived": false,
    "disabled": false,
    "open_issues_count": 8,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc2TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ["react", "typescript", "tailwindcss", "github-api", "visualization", "dashboard"],
    "visibility": "public",
    "forks": 142,
    "open_issues": 8,
    "watchers": 1280,
    "default_branch": "main"
  },
  {
    "id": 1300801,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMzAwODAx",
    "name": "boysenberry-repo-1",
    "full_name": "octocat/boysenberry-repo-1",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/boysenberry-repo-1",
    "description": "Testing repository setup for automated CI/CD workflows and action runners.",
    "fork": true,
    "url": "https://api.github.com/repos/octocat/boysenberry-repo-1",
    "created_at": "2024-05-04T10:00:00Z",
    "updated_at": "2025-11-12T11:20:00Z",
    "pushed_at": "2025-11-12T11:20:00Z",
    "git_url": "git://github.com/octocat/boysenberry-repo-1.git",
    "ssh_url": "git@github.com:octocat/boysenberry-repo-1.git",
    "clone_url": "https://github.com/octocat/boysenberry-repo-1.git",
    "homepage": null,
    "size": 204,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "JavaScript",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 3,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ["testing", "ci-cd", "actions"],
    "visibility": "public",
    "forks": 3,
    "open_issues": 0,
    "watchers": 12,
    "default_branch": "master"
  },
  {
    "id": 2154890,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMTU0ODkw",
    "name": "low-code-layout-builder",
    "full_name": "octocat/low-code-layout-builder",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/low-code-layout-builder",
    "description": "Visual drag-and-drop web layout builder emitting production-ready JSX & Tailwind CSS.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/low-code-layout-builder",
    "created_at": "2025-08-15T08:30:00Z",
    "updated_at": "2026-07-10T15:45:00Z",
    "pushed_at": "2026-07-22T14:10:00Z",
    "git_url": "git://github.com/octocat/low-code-layout-builder.git",
    "ssh_url": "git@github.com:octocat/low-code-layout-builder.git",
    "clone_url": "https://github.com/octocat/low-code-layout-builder.git",
    "homepage": "https://layoutcraft.io",
    "size": 3890,
    "stargazers_count": 890,
    "watchers_count": 890,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": true,
    "forks_count": 67,
    "archived": false,
    "disabled": false,
    "open_issues_count": 14,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc2TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": true,
    "web_commit_signoff_required": false,
    "topics": ["low-code", "ui-builder", "tailwindcss", "jsx-generator", "dnd"],
    "visibility": "public",
    "forks": 67,
    "open_issues": 14,
    "watchers": 890,
    "default_branch": "main"
  },
  {
    "id": 3491023,
    "node_id": "MDEwOlJlcG9zaXRvcnkzNDkxMDIz",
    "name": "custom-kernel-drivers",
    "full_name": "octocat/custom-kernel-drivers",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/custom-kernel-drivers",
    "description": "Experimental Linux kernel modules and IC driver bindings for touchscreen hardware.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/custom-kernel-drivers",
    "created_at": "2023-11-20T19:00:00Z",
    "updated_at": "2026-02-14T09:10:00Z",
    "pushed_at": "2026-03-01T17:25:00Z",
    "git_url": "git://github.com/octocat/custom-kernel-drivers.git",
    "ssh_url": "git@github.com:octocat/custom-kernel-drivers.git",
    "clone_url": "https://github.com/octocat/custom-kernel-drivers.git",
    "homepage": null,
    "size": 15400,
    "stargazers_count": 412,
    "watchers_count": 412,
    "language": "C",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 88,
    "archived": false,
    "disabled": false,
    "open_issues_count": 3,
    "license": {
      "key": "gpl-3.0",
      "name": "GNU General Public License v3.0",
      "spdx_id": "GPL-3.0",
      "url": "https://api.github.com/licenses/gpl-3.0",
      "node_id": "MDc2TGljZW5zZTk="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": true,
    "topics": ["linux-kernel", "c", "android-mod", "drivers", "hardware"],
    "visibility": "public",
    "forks": 88,
    "open_issues": 3,
    "watchers": 412,
    "default_branch": "main"
  },
  {
    "id": 4891002,
    "node_id": "MDEwOlJlcG9zaXRvcnk0ODkxMDAy",
    "name": "glassmorphic-design-system",
    "full_name": "octocat/glassmorphic-design-system",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/glassmorphic-design-system",
    "description": "Lightweight CSS utility library for matte styles, frosted glass cards, and dark themes.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/glassmorphic-design-system",
    "created_at": "2025-02-18T12:00:00Z",
    "updated_at": "2026-06-19T21:40:00Z",
    "pushed_at": "2026-06-20T10:05:00Z",
    "git_url": "git://github.com/octocat/glassmorphic-design-system.git",
    "ssh_url": "git@github.com:octocat/glassmorphic-design-system.git",
    "clone_url": "https://github.com/octocat/glassmorphic-design-system.git",
    "homepage": "https://glassui.design",
    "size": 890,
    "stargazers_count": 650,
    "watchers_count": 650,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 29,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc2TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ["css", "glassmorphism", "ui-components", "design-system", "dark-mode"],
    "visibility": "public",
    "forks": 29,
    "open_issues": 2,
    "watchers": 650,
    "default_branch": "main"
  },
  {
    "id": 5129910,
    "node_id": "MDEwOlJlcG9zaXRvcnk1MTI5OTEw",
    "name": "vite-inline-font-loader",
    "full_name": "octocat/vite-inline-font-loader",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/vite-inline-font-loader",
    "description": "Vite bundler plugin to automatically inline self-hosted web fonts and prevent render blocking.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/vite-inline-font-loader",
    "created_at": "2026-03-05T16:15:00Z",
    "updated_at": "2026-07-01T13:10:00Z",
    "pushed_at": "2026-07-02T11:50:00Z",
    "git_url": "git://github.com/octocat/vite-inline-font-loader.git",
    "ssh_url": "git@github.com:octocat/vite-inline-font-loader.git",
    "clone_url": "https://github.com/octocat/vite-inline-font-loader.git",
    "homepage": "https://www.npmjs.com/package/vite-inline-font-loader",
    "size": 420,
    "stargazers_count": 185,
    "watchers_count": 185,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": true,
    "forks_count": 11,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc2TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ["vite", "vite-plugin", "performance", "web-fonts", "javascript"],
    "visibility": "public",
    "forks": 11,
    "open_issues": 1,
    "watchers": 185,
    "default_branch": "main"
  },
  {
    "id": 6102938,
    "node_id": "MDEwOlJlcG9zaXRvcnk2MTAyOTM4",
    "name": "smooth-scroll-animations",
    "full_name": "octocat/smooth-scroll-animations",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/smooth-scroll-animations",
    "description": "Starter template showcasing Locomotive Scroll paired with Framer Motion page transitions.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/smooth-scroll-animations",
    "created_at": "2025-05-11T09:40:00Z",
    "updated_at": "2026-05-14T18:00:00Z",
    "pushed_at": "2026-05-15T08:20:00Z",
    "git_url": "git://github.com/octocat/smooth-scroll-animations.git",
    "ssh_url": "git@github.com:octocat/smooth-scroll-animations.git",
    "clone_url": "https://github.com/octocat/smooth-scroll-animations.git",
    "homepage": null,
    "size": 1150,
    "stargazers_count": 310,
    "watchers_count": 310,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 18,
    "archived": false,
    "disabled": false,
    "open_issues_count": 4,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc2TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": true,
    "web_commit_signoff_required": false,
    "topics": ["framer-motion", "locomotive-scroll", "animation", "react", "frontend"],
    "visibility": "public",
    "forks": 18,
    "open_issues": 4,
    "watchers": 310,
    "default_branch": "main"
  },
  {
    "id": 7820192,
    "node_id": "MDEwOlJlcG9zaXRvcnk3ODIwMTky",
    "name": "magisk-module-builder",
    "full_name": "octocat/magisk-module-builder",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/magisk-module-builder",
    "description": "CLI tool for packaging systemless Android root modifications and LSPosed modules.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/magisk-module-builder",
    "created_at": "2024-09-01T11:20:00Z",
    "updated_at": "2026-01-08T17:10:00Z",
    "pushed_at": "2026-01-08T17:10:00Z",
    "git_url": "git://github.com/octocat/magisk-module-builder.git",
    "ssh_url": "git@github.com:octocat/magisk-module-builder.git",
    "clone_url": "https://github.com/octocat/magisk-module-builder.git",
    "homepage": null,
    "size": 520,
    "stargazers_count": 225,
    "watchers_count": 225,
    "language": "Shell",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 35,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "gpl-3.0",
      "name": "GNU General Public License v3.0",
      "spdx_id": "GPL-3.0",
      "url": "https://api.github.com/licenses/gpl-3.0",
      "node_id": "MDc2TGljZW5zZTk="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ["magisk", "lsposed", "android", "shell", "systemless"],
    "visibility": "public",
    "forks": 35,
    "open_issues": 0,
    "watchers": 225,
    "default_branch": "main"
  },
  {
    "id": 8901234,
    "node_id": "MDEwOlJlcG9zaXRvcnk4OTAxMjM0",
    "name": "zustand-persisted-store-demo",
    "full_name": "octocat/zustand-persisted-store-demo",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/zustand-persisted-store-demo",
    "description": "Example repository demonstrating Zustand state slice management with LocalStorage sync.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/zustand-persisted-store-demo",
    "created_at": "2026-04-12T10:00:00Z",
    "updated_at": "2026-07-18T16:30:00Z",
    "pushed_at": "2026-07-18T16:30:00Z",
    "git_url": "git://github.com/octocat/zustand-persisted-store-demo.git",
    "ssh_url": "git@github.com:octocat/zustand-persisted-store-demo.git",
    "clone_url": "https://github.com/octocat/zustand-persisted-store-demo.git",
    "homepage": null,
    "size": 310,
    "stargazers_count": 94,
    "watchers_count": 94,
    "language": "TypeScript",
    "has_issues": false,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 5,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc2TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ["zustand", "react", "state-management", "typescript"],
    "visibility": "public",
    "forks": 5,
    "open_issues": 0,
    "watchers": 94,
    "default_branch": "main"
  },
  {
    "id": 9102934,
    "node_id": "MDEwOlJlcG9zaXRvcnk5MTAyOTM0",
    "name": "html-to-jsx-compiler",
    "full_name": "octocat/html-to-jsx-compiler",
    "private": false,
    "owner": {
      "login": "octocat",
      "id": 583231,
      "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
      "html_url": "https://github.com/octocat",
      "type": "User"
    },
    "html_url": "https://github.com/octocat/html-to-jsx-compiler",
    "description": "Parser utility that converts raw HTML string nodes into clean, formatted React JSX elements.",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/html-to-jsx-compiler",
    "created_at": "2025-10-02T14:10:00Z",
    "updated_at": "2026-06-25T19:20:00Z",
    "pushed_at": "2026-06-25T19:20:00Z",
    "git_url": "git://github.com/octocat/html-to-jsx-compiler.git",
    "ssh_url": "git@github.com:octocat/html-to-jsx-compiler.git",
    "clone_url": "https://github.com/octocat/html-to-jsx-compiler.git",
    "homepage": null,
    "size": 640,
    "stargazers_count": 142,
    "watchers_count": 142,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 12,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc2TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": ["jsx", "compiler", "ast", "html-parser", "javascript"],
    "visibility": "public",
    "forks": 12,
    "open_issues": 1,
    "watchers": 142,
    "default_branch": "main"
  }
];
// repoData= null			
export default repoData;